# Generated by Django 4.2.6 on 2023-10-25 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_remove_course_studants"),
        ("accounts", "0003_account_my_courses"),
        ("students_courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentsCourse",
            new_name="StudentCourse",
        ),
    ]
