# Generated by Django 4.2.6 on 2023-10-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students_courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="studants",
            field=models.ManyToManyField(
                related_name="my_courses",
                through="students_courses.StudentsCourse",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
