# Generated by Django 4.2.6 on 2023-10-25 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_studants_alter_course_instructor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="studants",
        ),
    ]
